import NavBarComponents from '@/components/NavBarComponents'
import './globals.css'
import { Inter } from 'next/font/google'
import FooterComponents from '@/components/FooterComponents'
import Category from '@/components/Category'
import SliderComponents from '@/components/SliderComponents'
import Pagination from '@/components/Pagination'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBarComponents/>
        {children}
        <FooterComponents/>
      </body>
    </html>
  )
}
